theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  logo:
    header: "/assets/images/logo.png"
    footer: "/assets/images/logo.png"
  breadcrumb:
    position: after-hero
  summary:
    position: hero