theme: osuny
_merge: deep
params:
  logo:
    header: "/assets/images/institut-design-logo-typo-header.svg"
    footer: "/assets/images/d-carre-blanc.svg"
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  home:
    head:
      title: site
  search:
    active: true
    positions:
      - primary