[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/equipe/leslie-hebert/roles/"
to = "/equipe/damien-serres/roles/"

[[redirects]]
from = "/equipe/leslie-hebert/programs/"
to = "/equipe/damien-serres/programs/"

[[redirects]]
from = "/agenda/commerce-connecte-parcours-design-et-innovation-sociale/"
to = "/agenda/offre-de-formation/commerce-connecte-parcours-design-et-innovation-sociale/"

[[redirects]]
from = "/equipe/leslie-hebert/"
to = "/equipe/damien-serres/"

[[redirects]]
from = "/agenda/design-et-societes-nouvelles/"
to = "/agenda/offre-de-formation/design-et-societes-nouvelles/"

[[redirects]]
from = "/institut-superieur-de-design-de-saint-malo/"
to = "/ecoles/institut-superieur-de-design-de-saint-malo/"

[[redirects]]
from = "/actualites/offre-de-formation/commerce-connecte-parcours-design-et-innovation-sociale/design-et-societes-nouvelles-bac-3/"
to = "/actualites/offre-de-formation/design-et-societes-nouvelles-bac-3/"

